//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:53:24 PM MMT 
//


package org.ace.insurance.ws.customer.messages;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.ace.insurance.ws.customer.model.BranchUpdate;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="branchUpdateList" type="{http://customer.model.web.insurance.ace.org}BranchUpdate" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "branchUpdateList",
    "latestVersionNo"
})
@XmlRootElement(name = "BranchUpdateResponse")
public class BranchUpdateResponse implements Serializable {

    @XmlElement(required = true)
    protected List<BranchUpdate> branchUpdateList;
    @XmlElement(required = true)
    protected int latestVersionNo;
    
    
    public int getLatestVersionNo() {
		return latestVersionNo;
	}

	public void setLatestVersionNo(int latestVersionNo) {
		this.latestVersionNo = latestVersionNo;
	}
    /**
     * Gets the value of the branchUpdateList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the branchUpdateList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBranchUpdateList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BranchUpdate }
     * 
     * 
     */
    public List<BranchUpdate> getBranchUpdateList() {
        if (branchUpdateList == null) {
            branchUpdateList = new ArrayList<BranchUpdate>();
        }
        return this.branchUpdateList;
    }

	public void setBranchUpdateList(List<BranchUpdate> branchUpdateList) {
		this.branchUpdateList = branchUpdateList;
	}
    
}
