//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:53:24 PM MMT 
//


package org.ace.insurance.ws.customer.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ace.insurance.web.service.customer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ace.insurance.web.service.customer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CountryUpdateResponse }
     * 
     */
    public CountryUpdateResponse createCountryUpdateResponse() {
        return new CountryUpdateResponse();
    }

    /**
     * Create an instance of {@link IndustryUpdateResponse }
     * 
     */
    public IndustryUpdateResponse createIndustryUpdateResponse() {
        return new IndustryUpdateResponse();
    }

    /**
     * Create an instance of {@link BankBranchUpdateRequest }
     * 
     */
    public BankBranchUpdateRequest createBankBranchUpdateRequest() {
        return new BankBranchUpdateRequest();
    }

    /**
     * Create an instance of {@link GetCustomerRequirementsResponse }
     * 
     */
    public GetCustomerRequirementsResponse createGetCustomerRequirementsResponse() {
        return new GetCustomerRequirementsResponse();
    }

    /**
     * Create an instance of {@link TownshipUpdateResponse }
     * 
     */
    public TownshipUpdateResponse createTownshipUpdateResponse() {
        return new TownshipUpdateResponse();
    }

    /**
     * Create an instance of {@link BankBranchUpdateResponse }
     * 
     */
    public BankBranchUpdateResponse createBankBranchUpdateResponse() {
        return new BankBranchUpdateResponse();
    }

    /**
     * Create an instance of {@link CountryUpdateRequest }
     * 
     */
    public CountryUpdateRequest createCountryUpdateRequest() {
        return new CountryUpdateRequest();
    }

    /**
     * Create an instance of {@link BranchUpdateRequest }
     * 
     */
    public BranchUpdateRequest createBranchUpdateRequest() {
        return new BranchUpdateRequest();
    }

    /**
     * Create an instance of {@link GetCustomerRequirementsRequest }
     * 
     */
    public GetCustomerRequirementsRequest createGetCustomerRequirementsRequest() {
        return new GetCustomerRequirementsRequest();
    }

    /**
     * Create an instance of {@link QualificationUpdateRequest }
     * 
     */
    public QualificationUpdateRequest createQualificationUpdateRequest() {
        return new QualificationUpdateRequest();
    }

    /**
     * Create an instance of {@link TownshipUpdateRequest }
     * 
     */
    public TownshipUpdateRequest createTownshipUpdateRequest() {
        return new TownshipUpdateRequest();
    }

    /**
     * Create an instance of {@link ReligionUpdateResponse }
     * 
     */
    public ReligionUpdateResponse createReligionUpdateResponse() {
        return new ReligionUpdateResponse();
    }

    /**
     * Create an instance of {@link BranchUpdateResponse }
     * 
     */
    public BranchUpdateResponse createBranchUpdateResponse() {
        return new BranchUpdateResponse();
    }

    /**
     * Create an instance of {@link RelationshipUpdateRequest }
     * 
     */
    public RelationshipUpdateRequest createRelationshipUpdateRequest() {
        return new RelationshipUpdateRequest();
    }

    /**
     * Create an instance of {@link AddNewCustomerResponse }
     * 
     */
    public AddNewCustomerResponse createAddNewCustomerResponse() {
        return new AddNewCustomerResponse();
    }

    /**
     * Create an instance of {@link RelationshipUpdateResponse }
     * 
     */
    public RelationshipUpdateResponse createRelationshipUpdateResponse() {
        return new RelationshipUpdateResponse();
    }

    /**
     * Create an instance of {@link ReligionUpdateRequest }
     * 
     */
    public ReligionUpdateRequest createReligionUpdateRequest() {
        return new ReligionUpdateRequest();
    }

    /**
     * Create an instance of {@link OccupationUpdateRequest }
     * 
     */
    public OccupationUpdateRequest createOccupationUpdateRequest() {
        return new OccupationUpdateRequest();
    }

    /**
     * Create an instance of {@link OccupationUpdateResponse }
     * 
     */
    public OccupationUpdateResponse createOccupationUpdateResponse() {
        return new OccupationUpdateResponse();
    }

    /**
     * Create an instance of {@link IndustryUpdateRequest }
     * 
     */
    public IndustryUpdateRequest createIndustryUpdateRequest() {
        return new IndustryUpdateRequest();
    }

    /**
     * Create an instance of {@link AddNewCustomerRequest }
     * 
     */
    public AddNewCustomerRequest createAddNewCustomerRequest() {
        return new AddNewCustomerRequest();
    }

    /**
     * Create an instance of {@link QualificationUpdateResponse }
     * 
     */
    public QualificationUpdateResponse createQualificationUpdateResponse() {
        return new QualificationUpdateResponse();
    }

}
