//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:53:24 PM MMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ace.org/ggip/customerService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.ace.insurance.ws.customer.messages;
