ALTER TABLE LIFEPROPOSAL
DROP COLUMN ISCHANNEL;

ALTER TABLE MEDICALPROPOSAL
DROP COLUMN ISCHANNEL;

ALTER TABLE TRAVELPROPOSAL
DROP COLUMN ISCHANNEL;

ALTER TABLE PERSONTRAVEL_PROPOSAL
DROP COLUMN ISCHANNEL;

ALTER TABLE LIFEPROPOSAL
ADD SALECHANNELTYPE varchar(255);

ALTER TABLE LIFEPOLICY
ADD SALECHANNELTYPE varchar(255);

ALTER TABLE MEDICALPROPOSAL
ADD SALECHANNELTYPE varchar(255);

ALTER TABLE MEDICALPOLICY
ADD SALECHANNELTYPE varchar(255);

ALTER TABLE TRAVELPROPOSAL
ADD SALECHANNELTYPE varchar(255);

ALTER TABLE PERSONTRAVEL_PROPOSAL
ADD SALECHANNELTYPE varchar(255);

ALTER TABLE PERSONTRAVEL_POLICY
ADD SALECHANNELTYPE varchar(255);