
CREATE TABLE BANCAASSURANCEPROPOSALHISTORY(
	[ID] [varchar](36) NOT NULL,
	[CHANNELID] [varchar](36) NULL,
	[BANCALICID] [varchar](36) NULL,
	[BANCAMETHODID] [varchar](36) NULL,
	[LIFEPROPOSALID] [varchar](36) NULL,
	[MEDICALPROPOSALID] [varchar](36) NULL,
	[TRAVELPROPOSALID] [varchar](36) NULL,
	[PERSONTRAVELPROPOSALID] [varchar](36) NULL,
	[BANCAREFFERALID] [varchar](36) NULL,
	[BANCABRMID] [varchar](36) NULL,
	[BANCABRANCHID] [varchar](36) NULL,
	[REFERENCEID] [char](36) NULL,
	[CREATEDUSERID] [char](36) NULL,
	[CREATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [char](36) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[VERSION] [int] NULL,
	[GROUPFARMERPROPOSALID] [char](36) NULL
	
) 

INSERT [ID_GEN] ([GEN_NAME], [GEN_VAL]) VALUES (N'BANCAASSURANCEPROPOSAL_HISTORY_GEN', 0)