//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.12 at 10:31:00 AM MMT 
//


package org.ace.insurance.ws.common.model.versionindex;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ace.insurance.web.model.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VersionRef_QNAME = new QName("http://www.ace.org/ggip/versionRefService", "VersionIndex");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ace.insurance.web.model.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VersionIndexDto }
     * 
     */
    public VersionIndexDto createVersionIndex() {
        return new VersionIndexDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionIndexDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ace.org/ggip/versionRefService", name = "VersionIndex")
    public JAXBElement<VersionIndexDto> createVersionIndex(VersionIndexDto value) {
        return new JAXBElement<VersionIndexDto>(_VersionRef_QNAME, VersionIndexDto.class, null, value);
    }
}
