-- 1. Delete BMI int values to change data type
UPDATE LIFEPROPOSAL_INSUREDPERSON_LINK
SET BMI = NULL
WHERE BMI != '';

-- 2. Change data type
ALTER TABLE LIFEPROPOSAL_INSUREDPERSON_LINK
ALTER COLUMN BMI NUMERIC(4,2) NULL;