//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.20 at 12:43:59 PM MMT 
//


package org.ace.insurance.ws.customer.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.ace.insurance.system.common.bankBranch.BankBranch;
import org.ace.insurance.system.common.branch.Branch;
import org.ace.insurance.system.common.country.Country;
import org.ace.insurance.system.common.industry.Industry;
import org.ace.insurance.system.common.occupation.Occupation;
import org.ace.insurance.system.common.qualification.Qualification;
import org.ace.insurance.system.common.religion.Religion;
import org.ace.insurance.system.common.township.Township;
import org.ace.insurance.ws.common.model.versionindex.VersionIndexDto;


/**
 * <p>Java class for CustomerRequirements complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerRequirements">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="branch" type="{http://dto.branch.common.system.insurance.ace.org}Branch" maxOccurs="unbounded"/>
 *         &lt;element name="bankBranch" type="{http://dto.bankBranch.common.system.insurance.ace.org}BankBranch" maxOccurs="unbounded"/>
 *         &lt;element name="qualification" type="{http://dto.qualification.common.system.insurance.ace.org}Qualification" maxOccurs="unbounded"/>
 *         &lt;element name="religion" type="{http://dto.religion.common.system.insurance.ace.org}Religion" maxOccurs="unbounded"/>
 *         &lt;element name="occupation" type="{http://dto.occupation.common.system.insurance.ace.org}Occupation" maxOccurs="unbounded"/>
 *         &lt;element name="industry" type="{http://dto.industry.common.system.insurance.ace.org}Industry" maxOccurs="unbounded"/>
 *         &lt;element name="country" type="{http://dto.country.common.system.insurance.ace.org}Country" maxOccurs="unbounded"/>
 *         &lt;element name="township" type="{http://dto.township.common.system.insurance.ace.org}Township" maxOccurs="unbounded"/>
 *         &lt;element name="relationship" type="{http://dto.relationship.common.system.insurance.ace.org}Relationship" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://dto.req.customer.service.web.insurance.ace.org}gender" maxOccurs="2" minOccurs="2"/>
 *         &lt;element ref="{http://dto.req.customer.service.web.insurance.ace.org}idType" maxOccurs="4" minOccurs="4"/>
 *         &lt;element ref="{http://dto.req.customer.service.web.insurance.ace.org}maritalStatus" maxOccurs="3" minOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerRequirements", propOrder = {
    "branch",
    "bankBranch",
    "qualification",
    "religion",
    "occupation",
    "industry",
    "country",
    "township",
    "relationship",
    "genders",
    "idTypes",
    "maritalStatuses",
    "versionIndexes"
})
@XmlRootElement(name="CustomerRequirements")
public class CustomerRequirements implements Serializable{
    
	private static final long serialVersionUID = 1L;
	@XmlElement(required = true)
    protected List<BranchDto> branch;
    @XmlElement(required = true)
    protected List<BankBranchDto> bankBranch;
    @XmlElement(required = true)
    protected List<QualificationDto> qualification;
    @XmlElement(required = true)
    protected List<ReligionDto> religion;
    @XmlElement(required = true)
    protected List<OccupationDto> occupation;
    @XmlElement(required = true)
    protected List<IndustryDto> industry;
    @XmlElement(required = true)
    protected List<CountryDto> country;
    @XmlElement(required = true)
    protected List<TownshipDto> township;
    @XmlElement(required = true)
    protected List<RelationshipDto> relationship;
    @XmlElement(required = true)
    protected List<String> genders;
    @XmlElement(required = true)
    protected List<String> idTypes;
    @XmlElement(required = true)
    protected List<String> maritalStatuses;
    @XmlElement(required = true)
    protected List<VersionIndexDto> versionIndexes;
    
    public CustomerRequirements() {
    }
        
    //To Construct before response sent to WS client
    public CustomerRequirements(List<BranchDto> branch,
			List<BankBranchDto> bankBranch,
			List<QualificationDto> qualification, List<ReligionDto> religion,
			List<OccupationDto> occupation, List<IndustryDto> industry,
			List<CountryDto> country, List<TownshipDto> township,
			List<RelationshipDto> relationship, List<String> genders,
			List<String> idTypes, List<String> maritalStatuses, List<VersionIndexDto> versionIndexes) {
		super();
		this.branch = branch;
		this.bankBranch = bankBranch;
		this.qualification = qualification;
		this.religion = religion;
		this.occupation = occupation;
		this.industry = industry;
		this.country = country;
		this.township = township;
		this.relationship = relationship;
		this.genders = genders;
		this.idTypes = idTypes;
		this.maritalStatuses = maritalStatuses;
		this.versionIndexes = versionIndexes;
	}

	/**
     * Gets the value of the branch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the branch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBranch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Branch }
     * 
     * 
     */
    public List<BranchDto> getBranch() {
        if (branch == null) {
            branch = new ArrayList<BranchDto>();
        }
        return this.branch;
    }

    /**
     * Gets the value of the bankBranch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankBranch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankBranch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankBranch }
     * 
     * 
     */
    public List<BankBranchDto> getBankBranch() {
        if (bankBranch == null) {
            bankBranch = new ArrayList<BankBranchDto>();
        }
        return this.bankBranch;
    }

    /**
     * Gets the value of the qualification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Qualification }
     * 
     * 
     */
    public List<QualificationDto> getQualification() {
        if (qualification == null) {
            qualification = new ArrayList<QualificationDto>();
        }
        return this.qualification;
    }

    /**
     * Gets the value of the religion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the religion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReligion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Religion }
     * 
     * 
     */
    public List<ReligionDto> getReligion() {
        if (religion == null) {
            religion = new ArrayList<ReligionDto>();
        }
        return this.religion;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the occupation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOccupation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Occupation }
     * 
     * 
     */
    public List<OccupationDto> getOccupation() {
        if (occupation == null) {
            occupation = new ArrayList<OccupationDto>();
        }
        return this.occupation;
    }

    /**
     * Gets the value of the industry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the industry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndustry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Industry }
     * 
     * 
     */
    public List<IndustryDto> getIndustry() {
        if (industry == null) {
            industry = new ArrayList<IndustryDto>();
        }
        return this.industry;
    }

    /**
     * Gets the value of the country property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the country property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Country }
     * 
     * 
     */
    public List<CountryDto> getCountry() {
        if (country == null) {
            country = new ArrayList<CountryDto>();
        }
        return this.country;
    }

    /**
     * Gets the value of the township property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the township property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTownship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Township }
     * 
     * 
     */
    public List<TownshipDto> getTownship() {
        if (township == null) {
            township = new ArrayList<TownshipDto>();
        }
        return this.township;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relationship }
     * 
     * 
     */
    public List<RelationshipDto> getRelationship() {
        if (relationship == null) {
            relationship = new ArrayList<RelationshipDto>();
        }
        return this.relationship;
    }
    
    public List<VersionIndexDto> getVersionIndexes() {
        if (versionIndexes == null) {
        	versionIndexes = new ArrayList<VersionIndexDto>();
        }
        return this.versionIndexes;
    }
    /**
     * Gets the value of the gender property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gender property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGender().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGenders() {
        if (genders == null) {
            genders = new ArrayList<String>();
        }
        return this.genders;
    }

    /**
     * Gets the value of the idType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIdTypes() {
        if (idTypes == null) {
            idTypes = new ArrayList<String>();
        }
        return this.idTypes;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the maritalStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaritalStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMaritalStatuses() {
        if (maritalStatuses == null) {
            maritalStatuses = new ArrayList<String>();
        }
        return this.maritalStatuses;
    }

}
