//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.13 at 03:53:24 PM MMT 
//

package org.ace.insurance.ws.customer.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import org.ace.insurance.common.FamilyInfo;
import org.ace.insurance.common.OfficeAddress;
import org.ace.insurance.common.PermanentAddress;
import org.ace.insurance.common.ResidentAddress;
import org.ace.insurance.system.common.bank.Bank;
import org.ace.insurance.system.common.bankBranch.BankBranch;
import org.ace.insurance.system.common.country.Country;
import org.ace.insurance.system.common.industry.Industry;
import org.ace.insurance.system.common.occupation.Occupation;
import org.ace.insurance.system.common.province.Province;
import org.ace.insurance.system.common.qualification.Qualification;
import org.ace.insurance.system.common.religion.Religion;
import org.ace.insurance.system.common.township.Township;
import org.aspectj.asm.internal.Relationship;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.ace.insurance.web.model.customer
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _RelationshipUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "RelationshipUpdate");
	private final static QName _Relationship_QNAME = new QName("http://www.ace.org/ggip/customerService", "Relationship");
	private final static QName _ResidentAddress_QNAME = new QName("http://www.ace.org/ggip/customerService", "ResidentAddress");
	private final static QName _Industry_QNAME = new QName("http://www.ace.org/ggip/customerService", "Industry");
	private final static QName _Name_QNAME = new QName("http://www.ace.org/ggip/customerService", "Name");
	private final static QName _ReligionUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "ReligionUpdate");
	private final static QName _FamilyInfo_QNAME = new QName("http://www.ace.org/ggip/customerService", "FamilyInfo");
	private final static QName _CustomerRequirements_QNAME = new QName("http://www.ace.org/ggip/customerService", "CustomerRequirements");
	private final static QName _IndustryUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "IndustryUpdate");
	private final static QName _Township_QNAME = new QName("http://www.ace.org/ggip/customerService", "Township");
	private final static QName _PermanentAddress_QNAME = new QName("http://www.ace.org/ggip/customerService", "PermanentAddress");
	private final static QName _Country_QNAME = new QName("http://www.ace.org/ggip/customerService", "Country");
	private final static QName _Province_QNAME = new QName("http://www.ace.org/ggip/customerService", "Province");
	private final static QName _QualificationUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "QualificationUpdate");
	private final static QName _BranchUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "BranchUpdate");
	private final static QName _Customer_QNAME = new QName("http://www.ace.org/ggip/customerService", "Customer");
	private final static QName _Religion_QNAME = new QName("http://www.ace.org/ggip/customerService", "Religion");
	private final static QName _Bank_QNAME = new QName("http://www.ace.org/ggip/customerService", "Bank");
	private final static QName _IdTypes_QNAME = new QName("http://www.ace.org/ggip/customerService", "idTypes");
	private final static QName _OfficeAddress_QNAME = new QName("http://www.ace.org/ggip/customerService", "OfficeAddress");
	private final static QName _Gender_QNAME = new QName("http://www.ace.org/ggip/customerService", "gender");
	private final static QName _OccupationUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "OccupationUpdate");
	private final static QName _BankBranch_QNAME = new QName("http://www.ace.org/ggip/customerService", "BankBranch");
	private final static QName _ContentInfo_QNAME = new QName("http://www.ace.org/ggip/customerService", "ContentInfo");
	private final static QName _Occupation_QNAME = new QName("http://www.ace.org/ggip/customerService", "Occupation");
	private final static QName _TownshipUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "TownshipUpdate");
	private final static QName _Genders_QNAME = new QName("http://www.ace.org/ggip/customerService", "genders");
	private final static QName _MaritalStatus_QNAME = new QName("http://www.ace.org/ggip/customerService", "maritalStatus");
	private final static QName _Branch_QNAME = new QName("http://www.ace.org/ggip/customerService", "Branch");
	private final static QName _BankBranchUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "BankBranchUpdate");
	private final static QName _IdType_QNAME = new QName("http://www.ace.org/ggip/customerService", "idType");
	private final static QName _MaritalStatuses_QNAME = new QName("http://www.ace.org/ggip/customerService", "maritalStatuses");
	private final static QName _Qualification_QNAME = new QName("http://www.ace.org/ggip/customerService", "Qualification");
	private final static QName _CountryUpdate_QNAME = new QName("http://www.ace.org/ggip/customerService", "CountryUpdate");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.ace.insurance.web.model.customer
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link PermanentAddress }
	 * 
	 */
	public PermanentAddressDto createPermanentAddress() {
		return new PermanentAddressDto();
	}

	/**
	 * Create an instance of {@link Religion }
	 * 
	 */
	public ReligionDto createReligion() {
		return new ReligionDto();
	}

	/**
	 * Create an instance of {@link ResidentAddress }
	 * 
	 */
	public ResidentAddressDto createResidentAddress() {
		return new ResidentAddressDto();
	}

	/**
	 * Create an instance of {@link ContentInfo }
	 * 
	 */
	public ContentInfoDto createCustomerContentInfo() {
		return new ContentInfoDto();
	}

	/**
	 * Create an instance of {@link Country }
	 * 
	 */
	public CountryDto createCountry() {
		return new CountryDto();
	}

	/**
	 * Create an instance of {@link Relationship }
	 * 
	 */
	public RelationshipDto createRelationship() {
		return new RelationshipDto();
	}

	/**
	 * Create an instance of {@link QualificationUpdate }
	 * 
	 */
	public QualificationUpdate createQualificationUpdate() {
		return new QualificationUpdate();
	}

	/**
	 * Create an instance of {@link OfficeAddress }
	 * 
	 */
	public OfficeAddressDto createOfficeAddress() {
		return new OfficeAddressDto();
	}

	/**
	 * Create an instance of {@link TownshipUpdate }
	 * 
	 */
	public TownshipUpdate createTownshipUpdate() {
		return new TownshipUpdate();
	}

	/**
	 * Create an instance of {@link Township }
	 * 
	 */
	public TownshipDto createTownship() {
		return new TownshipDto();
	}

	/**
	 * Create an instance of {@link ReligionUpdate }
	 * 
	 */
	public ReligionUpdate createReligionUpdate() {
		return new ReligionUpdate();
	}

	/**
	 * Create an instance of {@link Name }
	 * 
	 */
	public NameDto createName() {
		return new NameDto();
	}

	/**
	 * Create an instance of {@link CustomerRequirements }
	 * 
	 */
	public CustomerRequirements createCustomerRequirements() {
		return new CustomerRequirements();
	}

	/**
	 * Create an instance of {@link IndustryUpdate }
	 * 
	 */
	public IndustryUpdate createIndustryUpdate() {
		return new IndustryUpdate();
	}

	/**
	 * Create an instance of {@link Province }
	 * 
	 */
	public ProvinceDto createProvince() {
		return new ProvinceDto();
	}

	/**
	 * Create an instance of {@link BankBranch }
	 * 
	 */
	public BankBranchDto createBankBranch() {
		return new BankBranchDto();
	}

	/**
	 * Create an instance of {@link BankBranchUpdate }
	 * 
	 */
	public BankBranchUpdate createBankBranchUpdate() {
		return new BankBranchUpdate();
	}

	/**
	 * Create an instance of {@link Customer }
	 * 
	 */
	public CustomerDto createCustomer() {
		return new CustomerDto();
	}

	/**
	 * Create an instance of {@link FamilyInfo }
	 * 
	 */
	public FamilyInfoDto createFamilyInfo() {
		return new FamilyInfoDto();
	}

	/**
	 * Create an instance of {@link Branch }
	 * 
	 */
	public BranchDto createBranch() {
		return new BranchDto();
	}

	/**
	 * Create an instance of {@link Industry }
	 * 
	 */
	public IndustryDto createIndustry() {
		return new IndustryDto();
	}

	/**
	 * Create an instance of {@link OccupationUpdate }
	 * 
	 */
	public OccupationUpdate createOccupationUpdate() {
		return new OccupationUpdate();
	}

	/**
	 * Create an instance of {@link Occupation }
	 * 
	 */
	public OccupationDto createOccupation() {
		return new OccupationDto();
	}

	/**
	 * Create an instance of {@link RelationshipUpdate }
	 * 
	 */
	public RelationshipUpdate createRelationshipUpdate() {
		return new RelationshipUpdate();
	}

	/**
	 * Create an instance of {@link Bank }
	 * 
	 */
	public BankDto createBank() {
		return new BankDto();
	}

	/**
	 * Create an instance of {@link BranchUpdate }
	 * 
	 */
	public BranchUpdate createBranchUpdate() {
		return new BranchUpdate();
	}

	/**
	 * Create an instance of {@link CountryUpdate }
	 * 
	 */
	public CountryUpdate createCountryUpdate() {
		return new CountryUpdate();
	}

	/**
	 * Create an instance of {@link Qualification }
	 * 
	 */
	public QualificationDto createQualification() {
		return new QualificationDto();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link RelationshipUpdate }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "RelationshipUpdate")
	public JAXBElement<RelationshipUpdate> createRelationshipUpdate(RelationshipUpdate value) {
		return new JAXBElement<RelationshipUpdate>(_RelationshipUpdate_QNAME, RelationshipUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Relationship }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Relationship")
	public JAXBElement<RelationshipDto> createRelationship(RelationshipDto value) {
		return new JAXBElement<RelationshipDto>(_Relationship_QNAME, RelationshipDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ResidentAddress }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "ResidentAddress")
	public JAXBElement<ResidentAddressDto> createResidentAddress(ResidentAddressDto value) {
		return new JAXBElement<ResidentAddressDto>(_ResidentAddress_QNAME, ResidentAddressDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Industry }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Industry")
	public JAXBElement<IndustryDto> createIndustry(IndustryDto value) {
		return new JAXBElement<IndustryDto>(_Industry_QNAME, IndustryDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Name")
	public JAXBElement<NameDto> createName(NameDto value) {
		return new JAXBElement<NameDto>(_Name_QNAME, NameDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ReligionUpdate }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "ReligionUpdate")
	public JAXBElement<ReligionUpdate> createReligionUpdate(ReligionUpdate value) {
		return new JAXBElement<ReligionUpdate>(_ReligionUpdate_QNAME, ReligionUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link FamilyInfo }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "FamilyInfo")
	public JAXBElement<FamilyInfoDto> createFamilyInfo(FamilyInfoDto value) {
		return new JAXBElement<FamilyInfoDto>(_FamilyInfo_QNAME, FamilyInfoDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link CustomerRequirements }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "CustomerRequirements")
	public JAXBElement<CustomerRequirements> createCustomerRequirements(CustomerRequirements value) {
		return new JAXBElement<CustomerRequirements>(_CustomerRequirements_QNAME, CustomerRequirements.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link IndustryUpdate }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "IndustryUpdate")
	public JAXBElement<IndustryUpdate> createIndustryUpdate(IndustryUpdate value) {
		return new JAXBElement<IndustryUpdate>(_IndustryUpdate_QNAME, IndustryUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Township }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Township")
	public JAXBElement<TownshipDto> createTownship(TownshipDto value) {
		return new JAXBElement<TownshipDto>(_Township_QNAME, TownshipDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link PermanentAddress }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "PermanentAddress")
	public JAXBElement<PermanentAddressDto> createPermanentAddress(PermanentAddressDto value) {
		return new JAXBElement<PermanentAddressDto>(_PermanentAddress_QNAME, PermanentAddressDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Country }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Country")
	public JAXBElement<CountryDto> createCountry(CountryDto value) {
		return new JAXBElement<CountryDto>(_Country_QNAME, CountryDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Province }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Province")
	public JAXBElement<ProvinceDto> createProvince(ProvinceDto value) {
		return new JAXBElement<ProvinceDto>(_Province_QNAME, ProvinceDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link QualificationUpdate }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "QualificationUpdate")
	public JAXBElement<QualificationUpdate> createQualificationUpdate(QualificationUpdate value) {
		return new JAXBElement<QualificationUpdate>(_QualificationUpdate_QNAME, QualificationUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BranchUpdate }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "BranchUpdate")
	public JAXBElement<BranchUpdate> createBranchUpdate(BranchUpdate value) {
		return new JAXBElement<BranchUpdate>(_BranchUpdate_QNAME, BranchUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Customer }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Customer")
	public JAXBElement<CustomerDto> createCustomer(CustomerDto value) {
		return new JAXBElement<CustomerDto>(_Customer_QNAME, CustomerDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Religion }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Religion")
	public JAXBElement<ReligionDto> createReligion(ReligionDto value) {
		return new JAXBElement<ReligionDto>(_Religion_QNAME, ReligionDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Bank }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Bank")
	public JAXBElement<BankDto> createBank(BankDto value) {
		return new JAXBElement<BankDto>(_Bank_QNAME, BankDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "idTypes")
	public JAXBElement<String> createIdTypes(String value) {
		return new JAXBElement<String>(_IdTypes_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link OfficeAddress }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "OfficeAddress")
	public JAXBElement<OfficeAddressDto> createOfficeAddress(OfficeAddressDto value) {
		return new JAXBElement<OfficeAddressDto>(_OfficeAddress_QNAME, OfficeAddressDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "gender")
	public JAXBElement<String> createGender(String value) {
		return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link OccupationUpdate }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "OccupationUpdate")
	public JAXBElement<OccupationUpdate> createOccupationUpdate(OccupationUpdate value) {
		return new JAXBElement<OccupationUpdate>(_OccupationUpdate_QNAME, OccupationUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BankBranch }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "BankBranch")
	public JAXBElement<BankBranchDto> createBankBranch(BankBranchDto value) {
		return new JAXBElement<BankBranchDto>(_BankBranch_QNAME, BankBranchDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ContentInfo }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "ContentInfo")
	public JAXBElement<ContentInfoDto> createCustomerContentInfo(ContentInfoDto value) {
		return new JAXBElement<ContentInfoDto>(_ContentInfo_QNAME, ContentInfoDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Occupation }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Occupation")
	public JAXBElement<OccupationDto> createOccupation(OccupationDto value) {
		return new JAXBElement<OccupationDto>(_Occupation_QNAME, OccupationDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link TownshipUpdate }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "TownshipUpdate")
	public JAXBElement<TownshipUpdate> createTownshipUpdate(TownshipUpdate value) {
		return new JAXBElement<TownshipUpdate>(_TownshipUpdate_QNAME, TownshipUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "genders")
	public JAXBElement<String> createGenders(String value) {
		return new JAXBElement<String>(_Genders_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "maritalStatus")
	public JAXBElement<String> createMaritalStatus(String value) {
		return new JAXBElement<String>(_MaritalStatus_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Branch }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Branch")
	public JAXBElement<BranchDto> createBranch(BranchDto value) {
		return new JAXBElement<BranchDto>(_Branch_QNAME, BranchDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link BankBranchUpdate }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "BankBranchUpdate")
	public JAXBElement<BankBranchUpdate> createBankBranchUpdate(BankBranchUpdate value) {
		return new JAXBElement<BankBranchUpdate>(_BankBranchUpdate_QNAME, BankBranchUpdate.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "idType")
	public JAXBElement<String> createIdType(String value) {
		return new JAXBElement<String>(_IdType_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "maritalStatuses")
	public JAXBElement<String> createMaritalStatuses(String value) {
		return new JAXBElement<String>(_MaritalStatuses_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Qualification }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "Qualification")
	public JAXBElement<QualificationDto> createQualification(QualificationDto value) {
		return new JAXBElement<QualificationDto>(_Qualification_QNAME, QualificationDto.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link CountryUpdate }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ace.org/ggip/customerService", name = "CountryUpdate")
	public JAXBElement<CountryUpdate> createCountryUpdate(CountryUpdate value) {
		return new JAXBElement<CountryUpdate>(_CountryUpdate_QNAME, CountryUpdate.class, null, value);
	}

}
