 --ADD ENTITYID IN SALEMAN
ALTER TABLE SALEMAN
ADD ENTITYID varchar(255);

--ADD SALECHANNELTYPE IN GROUPFARMERPROPOSAL
ALTER TABLE GROUPFARMERPROPOSAL
ADD SALECHANNELTYPE varchar(255);

--ADD GROUPFARMERPROPOSALID IN BANCAASSURANCEPROPOSAL
ALTER TABLE BANCAASSURANCEPROPOSAL
ADD GROUPFARMERPROPOSALID varchar(255);

--ADD MEDICALPROPOSALID IN BANCAASSURANCEPROPOSAL
ALTER TABLE BANCAASSURANCEPROPOSAL
ADD MEDICALPROPOSALID varchar(255);

--UPDATE USERS SET DISABLED TO ZERO
UPDATE USERS
SET DISABLED='0'

--ADD PHONENO IN BANCAREFFERAL
ALTER TABLE BANCA_REFFERAL
ADD PHONE varchar(255);







